# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [5]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np

# Let's define a one-dimensional array 
list_1 = [1,3,4,5]
list_1

[1, 3, 4, 5]

In [7]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([1, 3, 4, 5])

In [8]:
type(my_numpy_array)

numpy.ndarray

In [84]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
my_matrix = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
my_matrix

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [13]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.1215103 , 0.20764717, 0.62310216, 0.83105934, 0.20597406,
       0.68419304, 0.06663543, 0.19498458, 0.78743991, 0.10789801,
       0.22594153, 0.35940954, 0.16449644, 0.69982339, 0.34567752,
       0.58299811, 0.66379835, 0.68330049, 0.5234715 , 0.48564271])

In [15]:
# you can create a matrix of random number as well
x = np.random.rand(20, 3)
x

array([[0.21512797, 0.70139258, 0.9785068 ],
       [0.2155917 , 0.8671114 , 0.35466711],
       [0.78817348, 0.5342167 , 0.26962048],
       [0.47949411, 0.88238784, 0.80730214],
       [0.04031818, 0.80658842, 0.91367346],
       [0.07139159, 0.30756154, 0.86440117],
       [0.89287422, 0.88947404, 0.94134301],
       [0.11105547, 0.48413344, 0.57019588],
       [0.69549136, 0.17169278, 0.00141129],
       [0.52406304, 0.14691947, 0.96977278],
       [0.66625169, 0.70474755, 0.02303667],
       [0.08934178, 0.26458402, 0.40696312],
       [0.54196327, 0.31316667, 0.30411191],
       [0.34756993, 0.40699587, 0.33192125],
       [0.91810856, 0.44900828, 0.64107732],
       [0.87170773, 0.64408505, 0.54444828],
       [0.96523197, 0.46551174, 0.13440436],
       [0.34394526, 0.07873783, 0.48510119],
       [0.59377758, 0.49056822, 0.98638707],
       [0.01787795, 0.85328715, 0.56604254]])

In [16]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

21

In [20]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(2, 4, 6)
x

array([3, 2, 3, 3, 2, 3])

In [21]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(2, 50)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
# Matrix of ones

x = np.ones((7, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Array of zeros
x = np.zeros((3,50))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

MINI CHALLENGE #2 
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [28]:
x = int(input("Insert number: "))
if x >= 0:
    print(np.random.randint(0, x, 10))
else:
    print("Please insert positive number!")

Insert number: 3
[2 0 2 2 0 1 2 2 0 2]


# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [31]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
z = np.exp(y)
z

array([8.10308393e+03, 3.26901737e+06, 5.45981500e+01])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [64]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])
diff = np.linalg.norm(x - y)
diff

18.33030277982336

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [66]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [67]:
# Access specific index from the numpy array
my_numpy_array[0]

3

In [71]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [75]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [77]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[1, 4, 4, 1],
       [6, 9, 6, 6],
       [1, 1, 2, 7],
       [2, 4, 4, 9]])

In [78]:
# Get a row from a mtrix
matrix[0]

array([1, 4, 4, 1])

In [94]:
# Get one element
matrix[0][3]

1

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [92]:
x = np.array([[2, 30, 20, -2, -2], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
x[4] = 0
x

array([[ 2, 30, 20, -2, -2],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [96]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[1, 9, 7, 9, 2],
       [5, 5, 6, 1, 6],
       [2, 3, 4, 1, 8],
       [8, 2, 3, 2, 2],
       [4, 6, 2, 7, 9]])

In [99]:
new_matrix = matrix[matrix > 7]
new_matrix

array([9, 9, 8, 8, 9])

In [100]:
# Obtain odd elements only
new_matrix = matrix[matrix % 2 == 1]
new_matrix

array([1, 9, 7, 9, 5, 5, 1, 3, 1, 3, 7, 9])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [106]:
x = np.array([[2, 30, 20, -2, -4], [3, 4, 40, -3, -2], 
             [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], 
             [13, 24, 22, 32, 37]])
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [111]:
import pandas as pd

In [113]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth': [15200, 29000, 10000, 2000],
                              'Years with Bank': [3, 4, 9, 5]})
bank_client_df

,Bank Client ID,Bank Client Name,Net Worth,Years with Bank
0,111,Chanel,15200,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [114]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [116]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

,Bank Client ID,Bank Client Name,Net Worth,Years with Bank
0,111,Chanel,15200,3
1,222,Steve,29000,4


In [117]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

,Bank Client ID,Bank Client Name,Net Worth,Years with Bank
2,333,Mitch,10000,9
3,444,Ryan,2000,5


MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [129]:
portfolio_df = pd.DataFrame({'Stock Ticker': ['AAPL', 'TSLA', 'GOOGL'],
                            'Company': ['Apple', 'Tesla', 'Alphabet'],
                            'Number of Shares': [20, 5, 8],
                            'Price per Share': [180, 250, 140]})
result = (portfolio_df['Number of Shares'] * portfolio_df['Price per Share']).sum()
portfolio_df.loc['Total'] = ['', '', '', result]
portfolio_df

,Stock Ticker,Company,Number of Shares,Price per Share
0,AAPL,Apple,20,180
1,TSLA,Tesla,5,250
2,GOOGL,Alphabet,8,140
Total,,,,5970


# TASK #7: PANDAS WITH CSV AND HTML DATA

In [133]:
# Pandas is used to read a csv file and store data in a DataFrame
df1 = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
df1[0]

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %
8,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...


In [135]:
df1[1]

,Province,Average House Price,12 Month Change
0,British Columbia,"$736,000",+ 7.6 %
1,Ontario,"$594,000",– 3.2 %
2,Alberta,"$353,000",– 7.5 %
3,Quebec,"$340,000",+ 7.6 %
4,Manitoba,"$295,000",– 1.4 %
5,Saskatchewan,"$271,000",– 3.8 %
6,Nova Scotia,"$266,000",+ 3.5 %
7,Prince Edward Island,"$243,000",+ 3.0 %
8,Newfoundland / Labrador,"$236,000",– 1.6 %
9,New Brunswick,"$183,000",– 2.2 %


In [ ]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [137]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df

HTTPError: HTTP Error 403: Forbidden

# TASK #8: PANDAS OPERATIONS

In [169]:
# Let's define a dataframe as follows:
df1 = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
df1 = df1[0]
df1

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %
8,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...


In [170]:
df1.drop(8, inplace = True)
df1

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %


In [171]:
df1['Average House Price'] = df1['Average House Price'].str.replace('$','', regex=False).str.replace(',', '', regex=False).astype(int)

In [172]:
df1

,City,Average House Price,12 Month Change
0,"Vancouver, BC",1036000,+ 2.63 %
1,"Toronto, Ont",870000,+10.2 %
2,"Ottawa, Ont",479000,+ 15.4 %
3,"Calgary, Alb",410000,– 1.5 %
4,"Montreal, Que",435000,+ 9.3 %
5,"Halifax, NS",331000,+ 3.6 %
6,"Regina, Sask",254000,– 3.9 %
7,"Fredericton, NB",198000,– 4.3 %


In [176]:
# Pick certain rows that satisfy a certain criteria 
df_expensive = df1[df1['Average House Price'] >= 300000]
df_expensive

,City,Average House Price,12 Month Change
0,"Vancouver, BC",1036000,+ 2.63 %
1,"Toronto, Ont",870000,+10.2 %
2,"Ottawa, Ont",479000,+ 15.4 %
3,"Calgary, Alb",410000,– 1.5 %
4,"Montreal, Que",435000,+ 9.3 %
5,"Halifax, NS",331000,+ 3.6 %


In [177]:
# Delete a column from a DataFrame
df_expensive.drop('12 Month Change', axis = 1, inplace = True)
df_expensive

,City,Average House Price
0,"Vancouver, BC",1036000
1,"Toronto, Ont",870000
2,"Ottawa, Ont",479000
3,"Calgary, Alb",410000
4,"Montreal, Que",435000
5,"Halifax, NS",331000


MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [184]:
bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth': [15200, 29000, 10000, 2000],
                              'Years with Bank': [3, 4, 9, 5]})
high_networth = bank_client_df[bank_client_df['Net Worth'] >= 5000]
result = high_networth['Net Worth'].sum()
result

54200

# TASK #9: PANDAS WITH FUNCTIONS

In [186]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [185]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [189]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [190]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [201]:
def triple_stock(stock_price):
    return (stock_price * 3 + 200)

In [206]:
portfolio_df['Tripled Price'] = portfolio_df['Price per Share'].apply(triple_stock)

In [207]:
portfolio_df

,Stock Ticker,Company,Number of Shares,Price per Share,Tripled Price
0,AAPL,Apple,20,180,740
1,TSLA,Tesla,5,250,950
2,GOOGL,Alphabet,8,140,620


In [209]:
total = (portfolio_df['Number of Shares'] * portfolio_df['Tripled Price']).sum()
portfolio_df.loc['Total'] = ['', '', '', '', total]
portfolio_df

,Stock Ticker,Company,Number of Shares,Price per Share,Tripled Price
0,AAPL,Apple,20,180,740
1,TSLA,Tesla,5,250,950
2,GOOGL,Alphabet,8,140,620
Total,,,,,24510


# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [210]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
0,111,Chanel,3500,3
1,222,Steve,29000,4
2,333,Mitch,10000,9
3,444,Ryan,2000,5


In [212]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank', ascending = False)

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
2,333,Mitch,10000,9
3,444,Ryan,2000,5
1,222,Steve,29000,4
0,111,Chanel,3500,3


In [215]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by = 'Years with bank', ascending = False, inplace = True)

In [216]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df

,Bank client ID,Bank Client Name,Net worth [$],Years with bank
2,333,Mitch,10000,9
3,444,Ryan,2000,5
1,222,Steve,29000,4
0,111,Chanel,3500,3


In [ ]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [221]:
df2 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']}, index = [0, 1, 2, 3])

In [222]:
df2

,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3


In [224]:
df3 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']}, index = [4, 5, 6, 7])

In [226]:
df3

,A,B,C,D
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7


In [227]:
df4 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'], 
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']}, index = [8, 9, 10, 11])

In [228]:
df4

,A,B,C,D
8,A8,B8,C8,D8
9,A9,B9,C9,D9
10,A10,B10,C10,D10
11,A11,B11,C11,D11


In [229]:
pd.concat([df2, df3, df4])

,A,B,C,D
0,A0,B0,C0,D0
1,A1,B1,C1,D1
2,A2,B2,C2,D2
3,A3,B3,C3,D3
4,A4,B4,C4,D4
5,A5,B5,C5,D5
6,A6,B6,C6,D6
7,A7,B7,C7,D7
8,A8,B8,C8,D8
9,A9,B9,C9,D9


# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [240]:
bank_df_1 = pd.DataFrame({'First Name': ['Adelle', 'Alicia', 'Alice', 'Angie', 'Beatrice'], 'Last Name': ['Hawthorne', 'Smith', 'Chen', 'Jolie', 'Cranberry'], 'ID': [1, 2, 3, 4, 5]})
bank_df_1

,First Name,Last Name,ID
0,Adelle,Hawthorne,1
1,Alicia,Smith,2
2,Alice,Chen,3
3,Angie,Jolie,4
4,Beatrice,Cranberry,5


In [241]:
bank_df_2 = pd.DataFrame({'First Name': ['Belle', 'Bee', 'Cathy', 'Callie', 'Damian'], 'Last Name': ['Agung', 'Suparman', 'Wahyu', 'Syahputra', 'Kingston'], 'ID': [6, 7, 8, 9, 10]})
bank_df_2

,First Name,Last Name,ID
0,Belle,Agung,6
1,Bee,Suparman,7
2,Cathy,Wahyu,8
3,Callie,Syahputra,9
4,Damian,Kingston,10


In [242]:
annual_salary = pd.DataFrame({'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10], 'Salary': [1000, 3493, 4993, 93839, 3444, 3000, 2034, 294049, 9000, 74643]})
annual_salary

,ID,Salary
0,1,1000
1,2,3493
2,3,4993
3,4,93839
4,5,3444
5,6,3000
6,7,2034
7,8,294049
8,9,9000
9,10,74643


In [257]:
df = pd.concat([bank_df_1, bank_df_2], ignore_index = True)
df

,First Name,Last Name,ID
0,Adelle,Hawthorne,1
1,Alicia,Smith,2
2,Alice,Chen,3
3,Angie,Jolie,4
4,Beatrice,Cranberry,5
5,Belle,Agung,6
6,Bee,Suparman,7
7,Cathy,Wahyu,8
8,Callie,Syahputra,9
9,Damian,Kingston,10


In [258]:
df['Full Name'] =df[['First Name', 'Last Name']].agg(' '.join, axis=1)
df.drop(['First Name', 'Last Name'], axis = 1, inplace = True)
df

,ID,Full Name
0,1,Adelle Hawthorne
1,2,Alicia Smith
2,3,Alice Chen
3,4,Angie Jolie
4,5,Beatrice Cranberry
5,6,Belle Agung
6,7,Bee Suparman
7,8,Cathy Wahyu
8,9,Callie Syahputra
9,10,Damian Kingston


In [259]:
client_salary = pd.merge(df, annual_salary, on = 'ID')
client_salary

,ID,Full Name,Salary
0,1,Adelle Hawthorne,1000
1,2,Alicia Smith,3493
2,3,Alice Chen,4993
3,4,Angie Jolie,93839
4,5,Beatrice Cranberry,3444
5,6,Belle Agung,3000
6,7,Bee Suparman,2034
7,8,Cathy Wahyu,294049
8,9,Callie Syahputra,9000
9,10,Damian Kingston,74643


In [265]:
new_client_df = pd.DataFrame({'ID': [11], 'Full Name': ['Shin Cen'], 'Salary': [10000000]})
bank_df_full = pd.concat([client_salary, new_client_df], ignore_index = True)
bank_df_full

,ID,Full Name,Salary
0,1,Adelle Hawthorne,1000
1,2,Alicia Smith,3493
2,3,Alice Chen,4993
3,4,Angie Jolie,93839
4,5,Beatrice Cranberry,3444
5,6,Belle Agung,3000
6,7,Bee Suparman,2034
7,8,Cathy Wahyu,294049
8,9,Callie Syahputra,9000
9,10,Damian Kingston,74643


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [65]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [139]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

KeyError: 'price per share [$]'

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [147]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

HTTPError: HTTP Error 403: Forbidden

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [266]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


,Bank Client ID,First Name,Last Name,Annual Salary [$/year]
0,1,Nancy,Rob,25000
1,2,Alex,Ali,35000
2,3,Shep,George,45000
3,4,Max,Mitch,48000
4,5,Allen,Steve,49000
5,6,Bill,Christian,32000
6,7,Dina,Mo,33000
7,8,Sarah,Steve,34000
8,9,Heather,Bob,23000
9,10,Holly,Michelle,22000


In [268]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

,Bank Client ID,First Name,Last Name,Annual Salary [$/year]
0,11,Ry,Aly,1000


In [269]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

,Bank Client ID,First Name,Last Name,Annual Salary [$/year]
0,1,Nancy,Rob,25000
1,2,Alex,Ali,35000
2,3,Shep,George,45000
3,4,Max,Mitch,48000
4,5,Allen,Steve,49000
5,6,Bill,Christian,32000
6,7,Dina,Mo,33000
7,8,Sarah,Steve,34000
8,9,Heather,Bob,23000
9,10,Holly,Michelle,22000
